export type Employee = {
  id: number,
  email: string,
  phone: string,
  isOnline: boolean,
  isDisabled: boolean,
  group: string,
  hostname: string,
  isAgentInstalled: boolean,
  lastComputer: string,
  lastSeen: string,
  rule: string,
  sId: string,
  tgAccount: string,
  token: string,
  getNameFromAd: boolean,
  isNotLicensed: boolean,
  position: string,
  firstName: string,
  lastName: string,
  userId: string,
  inDomain: boolean,
  face: string,
  address: string,
  userName: string,
  company: any
  computer: any
  user: any
  department: any
  employeeType: any
  country: any
}
